name: swisschema

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          elixir-version: "1.14.4"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

      - run: mix do deps.get + deps.compile
      - run: mix compile

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: _build
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          elixir-version: "1.14.4"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - run: mix format --check-formatted

  analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          elixir-version: "1.14.4"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - run: mix dialyzer

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          elixir-version: "1.14.4"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - run: mix test
